Revert "pinctrl: s32cc: implement GPIO functionality"
/tmp/next/build/drivers/pinctrl/nxp/pinctrl-s32cc.c: In function 's32_pinctrl_probe':
/tmp/next/build/drivers/pinctrl/nxp/pinctrl-s32cc.c:1565:33: error: assignment to 'int (*)(struct gpio_regmap *, enum gpio_regmap_operation,  unsigned int,  unsigned int,  unsigned int *, unsigned int *)' from incompatible pointer type 'int (*)(struct gpio_regmap *, unsigned int,  unsigned int,  unsigned int *, unsigned int *)' [-Wincompatible-pointer-types]
 1565 |         gpio_cfg.reg_mask_xlate = s32_gpio_reg_mask_xlate;
      |                                 ^

This reverts commit 94cb9e8f270797e489633cfa53d2d44afecb8bef.

Signed-off-by: Mark Brown <broonie@kernel.org>