Revert "panic: add panic_force_cpu= parameter to redirect panic to a specific CPU"
This reverts commit 090adee62cb6ad10d21b3804bd7e9c7930c41e7f due to

/tmp/next/build/kernel/panic.c:79:14: error: 'panic_force_buf' defined but not used [-Werror=unused-variable]
   79 | static char *panic_force_buf;
      |              ^~~~~~~~~~~~~~~

in allnoconfigs.

Signed-off-by: Mark Brown <broonie@kernel.org>